### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-backup#17]
The attached Word doc contains my suggested edits for the migrated release notes. Please let me know if you have any questions. Thanks!

[Cloud Backup Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-backup/files/31051/Cloud.Backup.Release.Notes_editsKH.docx)

**Comment by cyrichardson** [comment]
Applied Kelly's edits and published Release Notes (rst).
