### ISSUE TITLE
Changes to v2 Dev Guide - both rst and docbkx source

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-backup#38]
From: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Date: Thursday, January 14, 2016 at 9:27 AM
To: Bryan Davidson <bryan.davidson@RACKSPACE.COM>
Cc: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Subject: Re: Check on restorable query parameter

Thanks, Bryan. I will get to this soon and let the team know when the update is available.

—Catherine

From: Bryan Davidson <bryan.davidson@RACKSPACE.COM>
Date: Wednesday, January 13, 2016 at 3:19 PM
To: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Subject: Re: Check on restorable query parameter

Yes! It is a valid query parameter you should add to the RST source files. Sorry, I must’ve forgotten to note that addition to you whenever we made it.

Thanks for checking,
Bryan

From: Catherine Richardson <catherine.richardson@RACKSPACE.COM>
Date: Wednesday, January 13, 2016 at 9:59 AM
To: Bryan Davidson <bryan.davidson@rackspace.com>
Cc: Catherine Richardson <catherine.richardson@RACKSPACE.COM>
Subject: Check on restorable query parameter

Hi, Bryan,

I was checking the Cloud Backup v2 Dev Guide build against apiary and found a restorable query parameter in apiary for the method List configurations for a project.

When you have time, can you please confirm that I need to add it to the rst source files?

**Comment by cyrichardson** [comment]
@BryanSD Updated rst and docbkx source - changes are currently being built to docbkx source and will be published to docs-internal.rackspace.com shortly.

In addition to adding restorable query parm to list configurations for a project method, I also added: 

- v2/{project_id} to the 2 summary operations
- changed one occurrence of configuration_changes to configuration_changed.

**Comment by BryanSD** [comment]
Looks good - thanks @cyrichardson!
