### ISSUE TITLE
Internal doc migration

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-backup#62]
Determine whether the [Cloud Backup Developer Guide](http://docs-internal.rackspace.com/rcbu/api/v1.0/rcbu-devguide-v2/content/overview.html) needs to be migrated from docs-internal.rackspace.com website to the new docs-internal landing page.

If migration is required, please update this issue to reflect required work:

- [ ] Convert DocBook content to RST.  
- [ ] Create Sphinx project.  
- [ ] Set up for internal publishing (details coming soon)

**Comment by cyrichardson** [comment]
There is nothing for Cloud Backup v1 or v2 currently on docs-internal.rackspace.com that needs to be migrated/converted. At some point in the future the v2 Dev Guide will be on developer.rackspace.com. It is already in rst format. For now, I am providing the v2 URL to Development when reviews are needed. 

So this issue can be closed.
