### ISSUE TITLE
Note schedules use the iCalendar standard

### ISSUE THREAD

**Issue by BryanSD** [rackerlabs/docs-cloud-backup#66]
Under the `POST /v2/configurations` _Create a configuration_ endpoint, note that the example schedules use the iCalendar standard detailed [here](https://www.ietf.org/rfc/rfc2445.txt). However, fields are limited to what's seen in the examples.

**Comment by cyrichardson** [comment]
@BryanSD Would you like for me to add a note with a link to the iCalendar standard and with text indicating that fields are limited to those shown in the example? Thanks!

**Comment by BryanSD** [comment]
That would be great @cyrichardson!

**Comment by BryanSD** [comment]
Handled in #67
