### ISSUE TITLE
BackupConfigurationScheduled should be BackupConfigurationScheduleId

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/docs-cloud-backup#97]
This typo occurs [6 times](https://github.com/rackerlabs/docs-cloud-backup/search?utf8=%E2%9C%93&q=BackupConfigurationScheduled) in v1 docs.

As evidence of the appropriate spelling, the API responds with "BackupConfigurationScheduleId" when you actually send the GET described by the API docs.

    GET /v1.0/{tenant_id}/backup-configuration/{backupConfigurationId}
    ... "BackupConfigurationScheduleId": 123456

Also, this value is an integer, not a string. This is a pervasive error for many response/request values.

**Comment by meker12** [comment]
@joeashcraft  I fixed the spelling error. As far as the issues with the attribute type errors. Someone on the Cloud Backup development team would need to review and update the documentation.
